version: '3'
services:
  badhan-backup-service:
    container_name: badhan-backup-container
    build:
      context: .
    volumes:
      - '.:/badhan-backup'
      - './node_modules:/badhan-backup/node_modules'
    ports:
      - '4000:4000'
